version: "3.4"

services:

  server:
    build: .
    image: cloud-service-client-machine
    ports: 
      - 80:80
    environment:
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
