FROM adoptopenjdk/openjdk11:alpine-jre
EXPOSE 80
ARG JAR_FILE=/target/cloud-service-client-machine-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} cloud-machine-client.jar
ENTRYPOINT [ "java", "-jar", "-Dspring.profiles.active=dev","cloud-machine-client.jar"]
